export const Route = {
  FEED_STACK: "FEEDSTACK",
  ACCOUNT_STACK: "ACCOUNT_STACK",
  ARTICLES_READ: "ARTICLES_READ",

  ACCOUNT: "ACCOUNT",
  //doctor screen and tab

  FEED: "FEED",
  ARTICLES_READ:"ARTICLES_READ",

  //search screen and tab
  SEARCH: "SEARCH",
  SEARCH_TAB: "SEARCH_TAB",
  SEARCH_INPUT: "SEARCH_INPUT",
  SEARCH_RESULT: "SEARCH_RESULT",

  //profle screen and tab
  PROFILE: "PROFILE",
  PROFILE_TAB: "PROFILE_TAB",
  MAIN: "MAIN",

  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  ABOUT: "ABOUT",
  HELP: "HELP",
  LOGOUT: "LOGOUT",

  SERVICE_STACK: "SERVICESTACK",

  //setting
  ABOUTUS: "ABOUTUS",
  YOURSAATHI: "YOURSAATHI",
  YOURPACKAGES: "YOURPACKAGES",
};

//feed screen and tab
